### PR TITLE
Test Fixes

### PR DESCRIPTION
**Pull request by evancrow**
Fix issues with test after transitioning to the Overflow Menu from the Neeva Menu

### How was this tested?
- [ ] I tested this manually
- [ ] I added automated tests
- [x] Existing automated tests are enough to cover my changes

### CODE REVIEW

**Comment by evancrow** [comment]
Changed how the text was entered on the simulator since Paste & Go stopped working too. Now we just set the text of the TextField directly, a lot faster now though.

**Comment by evancrow** [comment]
Paste & Go seems to be fine on real devices though

**Review by darinwf — APPROVED** [review]
LG, and thanks for working on this, but what's the issue w/ iPad? Why do those tests need to be disabled? Is there a path for re-enabling them?

**Comment by evancrow** [comment]
I disabled tests for a couple reasons:

- `UIPasteboardExtensionsTests` and `URLEntry` were disabled for being flakey on CircleCI. I created issues for those if someone wants to spend time resolving the flakiness
- KeyboardShortcutTests were disabled on iPhone because iPhone doesn't support KeyboardShortcuts and it doesn't make sense to run them there

**Pull request merged**
