### PR TITLE
premium; avg monthly price i18n

### PR DESCRIPTION
**Pull request by jedireza**
This PR attempts to address a bug when we're displaying the average price per month for the annual plan.

In all other places we display prices, we're using `product.displayPrice` which includes formatting appropriate for the user's App Store local.

When we display the average price per month for the annual plan, we use a `NumberFormatter`. The display styles available from a number formatter can be found [here](https://developer.apple.com/documentation/foundation/numberformatter/style). Note: none of the formatting options will match the way `product.displayPrice` is formatted exactly 😕

For example if the App Store country is USA and the device region is set to UK, we divide the USD price by 12 and the `NumberFormatter` displays that value in Euros. This isn't just bad formatting, it's incorrect.

All is good when the app store country and region match.

As-is this PR isn't complete as it only handles the case where the App Store country is USA but the region isn't. I was really hoping we didn't need to maintain a bunch of custom formatting rules.

Maybe I missed another API available that would resolve this automatically. I also don't know how common it is for a users's App Store country to be different than their device region.

### How was this tested?
- [x] I tested this manually

### Manual test cases
Simulator.

### Screenshots and screen recordings
App Store United States with language and region settings changed.
image

## Issues addressed
N/A

### CODE REVIEW

**Comment by jedireza** [comment]
There is a `locale` property we could assign to our `NumberFormatter` ([docs here](https://developer.apple.com/documentation/foundation/numberformatter/1416967-locale))

Unfortunately the `storefront.countryCode` is a 3 character code of the country, not a value we can easily create a [`Locale`](https://developer.apple.com/documentation/foundation/locale) value out of.

**Comment by chung-lai** [comment]
> There is a `locale` property we could assign to our `NumberFormatter` ([docs here](https://developer.apple.com/documentation/foundation/numberformatter/1416967-locale))
> 
> Unfortunately the `storefront.countryCode` is a 3 character code of the country, not a value we can easily create a [`Locale`](https://developer.apple.com/documentation/foundation/locale) value out of.

Think I'm still not fully understand why we can't use [priceLocale](https://developer.apple.com/documentation/storekit/skproduct/1506145-pricelocale) similar to how it's being used [here](https://developer.apple.com/documentation/storekit/skproduct/1506094-price)

`priceLocale` is derived from the storefront

**Comment by jedireza** [comment]
I was really hoping this would be available. Here is the diff of my attempt:

```diff
iff --git a/Client/Frontend/Premium/PremiumStore.swift b/Client/Frontend/Premium/PremiumStore.swift
index e9746b233..667a90aac 100644
--- a/Client/Frontend/Premium/PremiumStore.swift
+++ b/Client/Frontend/Premium/PremiumStore.swift
@@ -364,15 +364,10 @@ class PremiumHelpers {
         }
     }

-    static func annualAvgPricePerMonth(from input: Decimal) -> String {
+    static func annualAvgPricePerMonth(_ product: Product) -> String {
         let formatter = NumberFormatter()
-        if let storefront = SKPaymentQueue.default().storefront {
-            formatter.currencyCode = storefront.countryCode
-            if storefront.countryCode == "USA" && Locale.current.regionCode != "US" {
-                formatter.currencySymbol = "US$"
-            }
-        }
+        formatter.locale = product.priceLocale
         formatter.numberStyle = .currency
-        return formatter.string(from: input / 12 as NSNumber) ?? "\(input / 12)"
+        return formatter.string(from: product.price / 12 as NSNumber) ?? "\(product.price / 12)"
     }
 }
diff --git a/Client/Frontend/Settings/Neeva/NeevaPremiumView.swift b/Client/Frontend/Settings/Neeva/NeevaPremiumView.swift
index 07c5650d9..ec839e6b0 100644
--- a/Client/Frontend/Settings/Neeva/NeevaPremiumView.swift
+++ b/Client/Frontend/Settings/Neeva/NeevaPremiumView.swift
@@ -82,7 +82,7 @@ struct NeevaPremiumView: View {
                         Text("Premium\nAnnual")
                             .font(.system(size: 16, weight: .bold))
                         Text(
-                            "\(PremiumHelpers.annualAvgPricePerMonth(from: annualProduct.price)) /mo"
+                            "\(PremiumHelpers.annualAvgPricePerMonth(annualProduct)) /mo"
                         )
                         .font(.system(size: 14))
                     }
diff --git a/Client/Frontend/SignInOrUpFlow/SignInOrUpFlowPlansView.swift b/Client/Frontend/SignInOrUpFlow/SignInOrUpFlowPlansView.swift
index 73d057246..49630189c 100644
--- a/Client/Frontend/SignInOrUpFlow/SignInOrUpFlowPlansView.swift
+++ b/Client/Frontend/SignInOrUpFlow/SignInOrUpFlowPlansView.swift
@@ -70,7 +70,7 @@ struct SignInOrUpFlowPlansView: View {
                         Text("Premium\nAnnual")
                             .font(.system(size: 16, weight: .bold))
                         Text(
-                            "\(PremiumHelpers.annualAvgPricePerMonth(from: annualProduct.price)) /mo"
+                            "\(PremiumHelpers.annualAvgPricePerMonth(annualProduct)) /mo"
                         )
                         .font(.system(size: 14))
                     }
diff --git a/Client/Frontend/WelcomeFlow/WelcomeFlowPlansView.swift b/Client/Frontend/WelcomeFlow/WelcomeFlowPlansView.swift
index 153f9dedf..5cb7a586d 100644
--- a/Client/Frontend/WelcomeFlow/WelcomeFlowPlansView.swift
+++ b/Client/Frontend/WelcomeFlow/WelcomeFlowPlansView.swift
@@ -70,7 +70,7 @@ struct WelcomeFlowPlansView: View {
                         Text("Premium\nAnnual")
                             .font(.system(size: 16, weight: .bold))
                         Text(
-                            "\(PremiumHelpers.annualAvgPricePerMonth(from: annualProduct.price)) /mo"
+                            "\(PremiumHelpers.annualAvgPricePerMonth(annualProduct)) /mo"
                         )
                         .font(.system(size: 14))
                     }
```

The compile error:
image

Some IDE context:
image

**Comment by chung-lai** [comment]
> I was really hoping this would be available. Here is the diff of my attempt:
> 
> ```diff
> iff --git a/Client/Frontend/Premium/PremiumStore.swift b/Client/Frontend/Premium/PremiumStore.swift
> index e9746b233..667a90aac 100644
> --- a/Client/Frontend/Premium/PremiumStore.swift
> +++ b/Client/Frontend/Premium/PremiumStore.swift
> @@ -364,15 +364,10 @@ class PremiumHelpers {
>          }
>      }
> 
> -    static func annualAvgPricePerMonth(from input: Decimal) -> String {
> +    static func annualAvgPricePerMonth(_ product: Product) -> String {
>          let formatter = NumberFormatter()
> -        if let storefront = SKPaymentQueue.default().storefront {
> -            formatter.currencyCode = storefront.countryCode
> -            if storefront.countryCode == "USA" && Locale.current.regionCode != "US" {
> -                formatter.currencySymbol = "US$"
> -            }
> -        }
> +        formatter.locale = product.priceLocale
>          formatter.numberStyle = .currency
> -        return formatter.string(from: input / 12 as NSNumber) ?? "\(input / 12)"
> +        return formatter.string(from: product.price / 12 as NSNumber) ?? "\(product.price / 12)"
>      }
>  }
> diff --git a/Client/Frontend/Settings/Neeva/NeevaPremiumView.swift b/Client/Frontend/Settings/Neeva/NeevaPremiumView.swift
> index 07c5650d9..ec839e6b0 100644
> --- a/Client/Frontend/Settings/Neeva/NeevaPremiumView.swift
> +++ b/Client/Frontend/Settings/Neeva/NeevaPremiumView.swift
> @@ -82,7 +82,7 @@ struct NeevaPremiumView: View {
>                          Text("Premium\nAnnual")
>                              .font(.system(size: 16, weight: .bold))
>                          Text(
> -                            "\(PremiumHelpers.annualAvgPricePerMonth(from: annualProduct.price)) /mo"
> +                            "\(PremiumHelpers.annualAvgPricePerMonth(annualProduct)) /mo"
>                          )
>                          .font(.system(size: 14))
>                      }
> diff --git a/Client/Frontend/SignInOrUpFlow/SignInOrUpFlowPlansView.swift b/Client/Frontend/SignInOrUpFlow/SignInOrUpFlowPlansView.swift
> index 73d057246..49630189c 100644
> --- a/Client/Frontend/SignInOrUpFlow/SignInOrUpFlowPlansView.swift
> +++ b/Client/Frontend/SignInOrUpFlow/SignInOrUpFlowPlansView.swift
> @@ -70,7 +70,7 @@ struct SignInOrUpFlowPlansView: View {
>                          Text("Premium\nAnnual")
>                              .font(.system(size: 16, weight: .bold))
>                          Text(
> -                            "\(PremiumHelpers.annualAvgPricePerMonth(from: annualProduct.price)) /mo"
> +                            "\(PremiumHelpers.annualAvgPricePerMonth(annualProduct)) /mo"
>                          )
>                          .font(.system(size: 14))
>                      }
> diff --git a/Client/Frontend/WelcomeFlow/WelcomeFlowPlansView.swift b/Client/Frontend/WelcomeFlow/WelcomeFlowPlansView.swift
> index 153f9dedf..5cb7a586d 100644
> --- a/Client/Frontend/WelcomeFlow/WelcomeFlowPlansView.swift
> +++ b/Client/Frontend/WelcomeFlow/WelcomeFlowPlansView.swift
> @@ -70,7 +70,7 @@ struct WelcomeFlowPlansView: View {
>                          Text("Premium\nAnnual")
>                              .font(.system(size: 16, weight: .bold))
>                          Text(
> -                            "\(PremiumHelpers.annualAvgPricePerMonth(from: annualProduct.price)) /mo"
> +                            "\(PremiumHelpers.annualAvgPricePerMonth(annualProduct)) /mo"
>                          )
>                          .font(.system(size: 14))
>                      }
> ```
> 
> The compile error: image
> 
> Some IDE context: image

Ah... 🤦 , guess the documentation is not up to date. While I was looking at the SKProduct class, I see there is an extension function `priceFormatStyle` which return a currency formatter in the storefront locale. There is an example usage in the function header doc. May be we can use that?

**Comment by chung-lai** [comment]
> > I was really hoping this would be available. Here is the diff of my attempt:
> > ```diff
> > iff --git a/Client/Frontend/Premium/PremiumStore.swift b/Client/Frontend/Premium/PremiumStore.swift
> > index e9746b233..667a90aac 100644
> > --- a/Client/Frontend/Premium/PremiumStore.swift
> > +++ b/Client/Frontend/Premium/PremiumStore.swift
> > @@ -364,15 +364,10 @@ class PremiumHelpers {
> >          }
> >      }
> > 
> > -    static func annualAvgPricePerMonth(from input: Decimal) -> String {
> > +    static func annualAvgPricePerMonth(_ product: Product) -> String {
> >          let formatter = NumberFormatter()
> > -        if let storefront = SKPaymentQueue.default().storefront {
> > -            formatter.currencyCode = storefront.countryCode
> > -            if storefront.countryCode == "USA" && Locale.current.regionCode != "US" {
> > -                formatter.currencySymbol = "US$"
> > -            }
> > -        }
> > +        formatter.locale = product.priceLocale
> >          formatter.numberStyle = .currency
> > -        return formatter.string(from: input / 12 as NSNumber) ?? "\(input / 12)"
> > +        return formatter.string(from: product.price / 12 as NSNumber) ?? "\(product.price / 12)"
> >      }
> >  }
> > diff --git a/Client/Frontend/Settings/Neeva/NeevaPremiumView.swift b/Client/Frontend/Settings/Neeva/NeevaPremiumView.swift
> > index 07c5650d9..ec839e6b0 100644
> > --- a/Client/Frontend/Settings/Neeva/NeevaPremiumView.swift
> > +++ b/Client/Frontend/Settings/Neeva/NeevaPremiumView.swift
> > @@ -82,7 +82,7 @@ struct NeevaPremiumView: View {
> >                          Text("Premium\nAnnual")
> >                              .font(.system(size: 16, weight: .bold))
> >                          Text(
> > -                            "\(PremiumHelpers.annualAvgPricePerMonth(from: annualProduct.price)) /mo"
> > +                            "\(PremiumHelpers.annualAvgPricePerMonth(annualProduct)) /mo"
> >                          )
> >                          .font(.system(size: 14))
> >                      }
> > diff --git a/Client/Frontend/SignInOrUpFlow/SignInOrUpFlowPlansView.swift b/Client/Frontend/SignInOrUpFlow/SignInOrUpFlowPlansView.swift
> > index 73d057246..49630189c 100644
> > --- a/Client/Frontend/SignInOrUpFlow/SignInOrUpFlowPlansView.swift
> > +++ b/Client/Frontend/SignInOrUpFlow/SignInOrUpFlowPlansView.swift
> > @@ -70,7 +70,7 @@ struct SignInOrUpFlowPlansView: View {
> >                          Text("Premium\nAnnual")
> >                              .font(.system(size: 16, weight: .bold))
> >                          Text(
> > -                            "\(PremiumHelpers.annualAvgPricePerMonth(from: annualProduct.price)) /mo"
> > +                            "\(PremiumHelpers.annualAvgPricePerMonth(annualProduct)) /mo"
> >                          )
> >                          .font(.system(size: 14))
> >                      }
> > diff --git a/Client/Frontend/WelcomeFlow/WelcomeFlowPlansView.swift b/Client/Frontend/WelcomeFlow/WelcomeFlowPlansView.swift
> > index 153f9dedf..5cb7a586d 100644
> > --- a/Client/Frontend/WelcomeFlow/WelcomeFlowPlansView.swift
> > +++ b/Client/Frontend/WelcomeFlow/WelcomeFlowPlansView.swift
> > @@ -70,7 +70,7 @@ struct WelcomeFlowPlansView: View {
> >                          Text("Premium\nAnnual")
> >                              .font(.system(size: 16, weight: .bold))
> >                          Text(
> > -                            "\(PremiumHelpers.annualAvgPricePerMonth(from: annualProduct.price)) /mo"
> > +                            "\(PremiumHelpers.annualAvgPricePerMonth(annualProduct)) /mo"
> >                          )
> >                          .font(.system(size: 14))
> >                      }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The compile error: image
> > Some IDE context: image
> 
> Ah... 🤦 , guess the documentation is not up to date, thanks for checking! While I was looking at the SKProduct class, I see there is an extension function `priceFormatStyle` which return a currency formatter in the storefront locale. There is an example usage in the function header doc. May be we can use that? But i'm not entirely sure how to convert `Decimal.FormatStyle.Currency` to `NumberFormatter.Style`, if this doesn't work, i don't have any other idea 😓

Oh, may be we can get `locale` from `Decimal.FormatStyle.Currency` so we can get the locale by `product.priceFormatStyle.locale`? 🤞

**Comment by jedireza** [comment]
Nice find. With that approach we do have a correct USD value, however the formatting is not the same as `product.displayPrice` and it's not respecting the `,` vs `.` separator for a particular region.

image

**Comment by chung-lai** [comment]
> Nice find. With that approach we do have a correct USD value, however the formatting is not the same as `product.displayPrice` and it's not respecting the `,` vs `.` separator for a particular region.
> 
> image

Right, not sure what to do with the formatting but at least it would be the right locale.

**Comment by jedireza** [comment]
> Right, not sure what to do with the formatting but at least it would be the right locale.

I agree. This keeps our code simple enough and fixed the main bug.

**Review by chung-lai — APPROVED** [review]
LGTM, thanks for taking care of this!

**Comment by chung-lai** [comment]
Do we need the cherry-pick label?

**Pull request merged**
