### PR TITLE
Keep Pinned Tabs in Today

### PR DESCRIPTION
**Pull request by evancrow**
Makes sure pinned tabs are always considered last executed today.

### How was this tested?
- [x] I tested this manually

### CODE REVIEW

**Review by chassu — CHANGES_REQUESTED** [review]
nits: can you modify the function name so it's inclusive of this edge case? e.x. `isPinnedTodayOrWasLastExecuted`

See discussion here: https://github.com/neevaco/neeva-ios/pull/3870/files

**Comment by evancrow** [comment]
> https://github.com/neevaco/neeva-ios/pull/3870/files

Per the conversation, I opted to add a more descriptive comment :)
#
I also made tab pinning a lot smoother. Unfortunately SwiftUI ContextMenus keep their preview around even after it dismisses so a tiny delay makes pinning look better. @darinwf, unfortunately I had to use an `asyncAfter` to make this better.

Before:

https://user-images.githubusercontent.com/37356984/181155548-53765352-79b0-4432-aee1-6c4f97648874.mp4

After:

https://user-images.githubusercontent.com/37356984/181155570-580121fd-61ad-44c7-af1e-091b8bf9fbc6.mp4

**Comment by chassu** [comment]
In the conversation, I thought about adding comments too, but @darinwf thought it wasn't the best idea. Pinging him for his thoughts here.

**Review by chassu — APPROVED** [review]
LGTM!

**Pull request merged**
