### PR TITLE
Add frame and instruction to qr code scanner

### PR DESCRIPTION
**Pull request by yasminyin96**
* Add frame to show a box-like viewfinder
* Add instruction label to the bottom of scanner
* Vibrate on scan

### How was this tested?
- [X] I tested this manually

### Screenshots and screen recordings
Camera access denied

https://user-images.githubusercontent.com/104786010/172495819-bf7b6967-8490-4bc8-90bd-9599dc24d018.MP4

Invalid and valid code scan

https://user-images.githubusercontent.com/104786010/172495850-ff917ab0-d1de-44bd-aa64-a508170298ea.MP4

### CODE REVIEW

**Comment by yasminyin96** [comment]
@hwiatneeva  
I added the frame and instruction label for the scanner view. Please have a look if you have time. Thank you so much.

**Comment by hwiatneeva** [comment]
sorry for the super delay -- i did try the flag, and will document my input. 

Separate/related isse:
in the meantime, i know it's not the ios scope, but web scope, but there's an issue on the web:
- Settings > QR Code **signs me out** (both my hwi@neeva.co and google sso hwileedesign@gmail) before it shows the modal. I continue to re-sign-in. 

Where do we file an issue for the web? @yasminyin96 @chung-lai   TY!!

**Comment by yasminyin96** [comment]
> sorry for the super delay -- i did try the flag, and will document my input.
> 
> Separate/related isse: in the meantime, i know it's not the ios scope, but web scope, but there's an issue on the web:
> 
> * Settings > QR Code **signs me out** (both my [hwi@neeva.co](mailto:hwi@neeva.co) and google sso hwileedesign@gmail) before it shows the modal. I continue to have to re-sign-in.
> 
> @yasminyin96 @chung-lai
> 
> * Could you test and verify this is a persistent issue on the web?
> * Where do we file an issue for the web? TY!!

I filed this issue before: https://github.com/neevaco/neeva-ios/issues/3615
But I thought it was fixed. I will reopen this issue.

**Comment by yasminyin96** [comment]
There seems to be more work for this. Close this for now and revisit later.

**Pull request closed without merging**
