### PR TITLE
Update Readability (Cookie Cutter)

### PR DESCRIPTION
**Pull request by evancrow**
Fixed: #3671

### CODE REVIEW

**Review by chung-lai — COMMENTED** [review]
The change looks good to me and works on my machine :)

Would love a review from @darinwf who may be more familiar with our yarn packaging system. For context, without changing that readability package, we couldn't run `yarn install && yarn build`.

**Comment by chung-lai** [comment]
> The change looks good to me and works on my machine :)
> 
> Would love a review from @darinwf who may be more familiar with our yarn packaging system. For context, without changing that readability package, we couldn't run `yarn install && yarn build`.

Well looks like last time that readability package update was 3 years ago 😓 And readability is for reader mode, may want to verify it's still functioning as expected.

**Comment by evancrow** [comment]
Reader mode is still good!

**Review by chung-lai — APPROVED** [review]
LGTM

**Comment by evancrow** [comment]
@darinwf This is pretty low risk so I'm going to merge to get this on main.

**Pull request merged**
