### PR TITLE
Fix image context menu loading indicator

### PR DESCRIPTION
**Pull request by buracules**
- Fixed loading indicator problem in image context menu

### How was this tested?
- [x] I tested this manually
- [ ] I added automated tests
- [ ] Existing automated tests are enough to cover my changes

#### Before
https://user-images.githubusercontent.com/15333612/171733248-01f98cf2-832d-4720-a33f-6c7ac54d88a8.mp4

#### After
https://user-images.githubusercontent.com/15333612/171733308-672a5b1b-5c6c-4173-9294-39737f15bfc5.mp4

### CODE REVIEW

**Comment by darinwf** [comment]
I'm a little confused about what problem is being solved. I'm not sure I see the differences between the two videos. Must be just missing it!

**Comment by chassu** [comment]
In the first video, the UI looks glitched out for a split second before the context menu shows up.

**Comment by buracules** [comment]
Screen Shot 2022-06-03 at 07 35 28
This is from first video @darinwf

**Comment by evancrow** [comment]
Prematurely stamped

**Review by darinwf — APPROVED** [review]
LGTM, thanks! (Sorry for the delay in reviewing!)

**Pull request merged**
