### PR TITLE
Hide Neeva Search when suggestion fails

### PR DESCRIPTION
**Pull request by yasminyin96**
* Hide Neeva Search when suggestion fails

### How was this tested?
- [X] I tested this manually

## Issues addressed
* https://github.com/neevaco/neeva-ios/issues/3645

### CODE REVIEW

**Comment by yasminyin96** [comment]
Do we need to show offline error view if the suggestion fails due to offline?


With other errors, do we need show the error under the Neeva Search row, or just hide it?

**Comment by chung-lai** [comment]
> Should we show offline error view if the suggestion fails due to offline? 
> 

For the offline case, I think having an offline screen makes sense since user can't do much in the browser if they are offline :)

> With other errors, do we need show the error under the Neeva Search row, or just hide it? 

Having some type of error like "Neeva Search is not available" or other graceful message will help user on questioning why there is no Neeva suggestion. Any thought, @hwiatneeva @yozuysal ?

**Review by chung-lai — COMMENTED** [review]
Code LGTM, let's see what others think about the open question

**Comment by chung-lai** [comment]
There seems to be more work need to be there for this. Let's close for now and revisit later.

**Pull request closed without merging**
