### PR TITLE
Hide Overlay When Opening URL

### PR DESCRIPTION
**Pull request by evancrow**
Fixed: #2912

### CODE REVIEW

**Comment by evancrow** [comment]
This openURLInNewTab path is called whenever a URL is opened from outside the app, or from a Neeva app element (i.e. help center)

**Comment by EdwardJTL** [comment]
if we open a link to a page that is already in a tab, we switch tab but the overlay is still open

**Comment by evancrow** [comment]
Hm, maybe it makes more sense to add this to `switchToOrCreateTab` then

**Review by EdwardJTL — APPROVED** [review]
nit: theres white space on line 954

**Pull request merged**
