### PR TITLE
time based switcher pt 2

### PR DESCRIPTION
**Pull request by chassu**
add archived tab settings view and fix for cookie cutter settings

### How was this tested?
- [x] Existing automated tests are enough to cover my changes

### Screenshots and screen recordings

Uploading Simulator Screen Recording - iPhone 13 Pro - 2022-04-14 at 18.14.52.mp4…

### CODE REVIEW

**Comment by chassu** [comment]
I added an option to shorten the demotion time from a day to 15 seconds for testing purposes.

Follow-ups:

- Only set flags to true when old tabs are selected
- HistoryView
- Add top padding to scrollView
- Enable a state where no tab is selected

**Comment by chassu** [comment]
https://user-images.githubusercontent.com/87332917/163767236-7849c135-8dda-46a0-bb46-93249c406981.mp4

**Comment by evancrow** [comment]
I enabled the flag, all works well! Except for one thing, seeing this when the flag is disabled:

Simulator Screen Shot - iPhone 13 Pro - 2022-04-18 at 20 11 31

**Review by evancrow — APPROVED** [review]
Tried it out, really solid!

**Comment by evancrow** [comment]
Actually, I found that the text above the settings option does not change based on what the user has selected. It's static as "Neeva is set to keep tabs for 30 days".

**Review by evancrow — APPROVED** [review]
LGTM

**Pull request merged**
