### PR TITLE
Disable Card Close Button When Animate is False

### PR DESCRIPTION
**Pull request by evancrow**
Fixes a bug where the close button would animate while scrolling the CardGrid. Should only animate with the `CardTransitionModel`.

### How was this tested?
- [x] I tested this manually

### CODE REVIEW

**Comment by darinwf** [comment]
Can you add a description to this PR? What bug is this fixing? Thanks!

**Comment by evancrow** [comment]
Updated!

**Comment by darinwf** [comment]
How do I repro the bug being fixed?

**Comment by evancrow** [comment]
Trying to get a screen recording, flakey, but here's the repro (latest TestFlight):

- Lots of tabs in CardGrid
- Scroll top/bottom & vice versa:
- Close button for every tab will sometimes slide in

**Review by darinwf — APPROVED** [review]
Thanks, makes sense.

**Pull request merged**
