### PR TITLE
Default Browser interstitial experiment 

### PR DESCRIPTION
**Pull request by chung-lai**
Default browser interstitial experiment

What's included (besides the variant arms changes):

* Redo the bottom buttons view in ZStack so the button doesn't move around between screens and always stick to the bottom
* Redo the reusable interstitial screen to make it more flexible to support various view layouts

### How was this tested?
- [x] I tested this manually
- [ ] I added automated tests
- [ ] Existing automated tests are enough to cover my changes

Video:

https://user-images.githubusercontent.com/87332578/173672419-3dc1bda8-6e2d-4b4a-ac63-ebc06f986482.mov

| Welcome | Screen 2 | Screen 2.5 |
| --- | --- | --- |
|  Screen Shot 2022-06-14 at 12 13 56 PM | Screen Shot 2022-06-14 at 12 13 58 PM | Screen Shot 2022-06-14 at 12 14 00 PM |
| Screen Shot 2022-06-14 at 12 15 46 PM | Screen Shot 2022-06-14 at 12 15 49 PM | Screen Shot 2022-06-14 at 12 15 51 PM |
| Screen Shot 2022-06-14 at 12 16 40 PM | Screen Shot 2022-06-14 at 12 16 43 PM | Screen Shot 2022-06-14 at 12 16 45 PM | 
| Screen Shot 2022-06-14 at 12 26 42 PM | Screen Shot 2022-06-14 at 12 26 45 PM | Screen Shot 2022-06-14 at 12 26 46 PM |

**Control:**
| Control Screen 1 | Control Screen 2 |
| --- | --- |
| Screen Shot 2022-06-14 at 12 48 07 AM  | Screen Shot 2022-06-14 at 12 48 09 AM |

### CODE REVIEW

**Comment by chung-lai** [comment]
@hwiatneeva, @bikramneeva. Would love a review on all the screens' layout and the flow (including the animation).

**Comment by chung-lai** [comment]
@hwiatneeva, will need asset for the gradient background for the variant arm

**Comment by hwiatneeva** [comment]
Thx @chung-lai !  Pls zoom anytime for anything.

**Screen 1**
* Background gradient:  This test used different BG gradient (the control bg is lighter blue). Could we swap with one of the following made for this test (short and tall since i'm unsure how bg is positioned):
gradient-tall
gradient-short

* Logo + Card:   Tricky layout for screen sizes! 
** Need to vertical-center position the card 
** Logo, if possible, vertical-center in the given vertical space
image


**Screen 2**
* Headline:  Make Neeva Your Defaul Browser **to**  <-- add 'to'
* Arrow:  remove

**Comment by hwiatneeva** [comment]
Nit - tablet Screen 1 bug -- CTA should be "Let's Go" not Get Started
image

The rest -- LGTM. TY @chung-lai !!!

**Comment by chung-lai** [comment]
> Nit - tablet Screen 1 bug -- CTA should be "Let's Go" not Get Started image
> 
> The rest -- LGTM. TY @chung-lai !!!

Good catch, thank you @hwiatneeva. Haha.. 🙈  after looking at all these various screens lol

**Comment by bikramneeva** [comment]
@chung-lai  animation/copy lgtm no other changes

**Review by jedireza — APPROVED** [review]
Code looks good.

**Pull request merged**
