### PR TITLE
Keyboard SafeArea Fixes

### PR DESCRIPTION
**Pull request by evancrow**
Fix some cases where the keyboard would hide content. Be careful when using `ignoreSafeArea`!

### CODE REVIEW

**Review by darinwf — CHANGES_REQUESTED** [review]
Actually, I tested this and now I'm seeing the bottom bar show up above the keyboard on linkedin.com:

Screen Shot 2022-02-10 at 9 33 24 PM

**Comment by darinwf** [comment]
It is not consistent.. the bottom bar doesn't always appear above the keyboard. really strange.

**Comment by evancrow** [comment]
@darinwf That was caused by switching form one textfield to another, causing the view to update when it was not necessary and somehow that caused the keyboard height to get set to 0.

**Review by darinwf — APPROVED** [review]
Tested it out on linkedin.com, and it works great. Thanks!

**Pull request merged**
