### PR TITLE
Combine Education screen into DB interstitial

### PR DESCRIPTION
**Pull request by chung-lai**
We want to start an experiment on showing educational material on how to set default browser in the interstitial screen. Mock: https://www.figma.com/file/73UbU5MtJvIJtvTz3HyvHE/Default-Browser-Prompt?node-id=0%3A1

The main reason of building a new interstitial view instead of nesting different style into the same view because it's an experiment and there is not much shared logic, it will be easy to just delete the other view once we decide which one to launch.

### How was this tested?
- [x] I tested this manually
- [ ] I added automated tests
- [ ] Existing automated tests are enough to cover my changes

### Manual test cases
If manually tested, describe the different scenarios you followed to ensure
that your changes work.  Make sure that you've tested as many pathways as
possible -- not just the [happy path](https://en.wikipedia.org/wiki/Happy_path).

### Screenshots a

iPhone 12
Screen Shot 2022-03-08 at 6 03 42 PM

iPhone 8
Screen Shot 2022-03-08 at 6 01 53 PM

iPad
Screen Shot 2022-03-08 at 5 07 53 PM

## Issues addressed
* Link(s) to Github issue(s) (if applicable)

### CODE REVIEW

**Review by hwiatneeva — COMMENTED** [review]
LGTM from design. I don't do code approval. Thanks Chung!!!!!

Side note for myself:  Going forward, I need to learn how the layout works for different screens, e.g. what to indicate in the design in order to make certain part stretchable, sticky, etc (a new area to me).

**Comment by chung-lai** [comment]
> LGTM from design. I don't do code approval. Thanks Chung!!!!!
> 
> Side note for myself: Going forward, I need to learn how the layout works for different screens, e.g. what to indicate in the design in order to make certain part stretchable, sticky, etc (a new area to me).

Thanks Hwi! Screen size is always the tricky one, I tried to follow the padding in the mock but couldn't do those exactly without much hacking. End up using the system spacing for a couple of the large paddings in order for different screen to work :D

**Review by darinwf — APPROVED** [review]
LGTM

Separately and if we are happy with how this performs, we should update the educational UI shown when tapping on Default Browser in our Settings.

**Comment by darinwf** [comment]
@chung-lai - would be good to spot check that this works properly on iPad too.

**Comment by chung-lai** [comment]
> @chung-lai - would be good to spot check that this works properly on iPad too.

Oh, right. I took a screenshot and forgot to post.

**Comment by hwiatneeva** [comment]
> 



> > @chung-lai - would be good to spot check that this works properly on iPad too.
> 
> Oh, right. I took a screenshot and forgot to post. Updated the screenshots

LGTM. Thanks Chung!

**Pull request merged**
