### PR TITLE
Add Find Tab in CardGrid OverflowMenu

### PR DESCRIPTION
**Pull request by evancrow**
- Creates a generic `FindView`
- Adds option to open the Find Tab menu from `CardGrid` 
- Search for tab code

### How was this tested?
- [x] I added automated tests

### Screenshots and screen recordings

https://user-images.githubusercontent.com/37356984/167012874-de25877d-a2a9-4a4f-84d7-ac30323a314f.mp4

## Issues addressed
Fixed: #3504

### CODE REVIEW

**Comment by evancrow** [comment]
cc @hwiatneeva on design

**Comment by darinwf** [comment]
Nice! This should probably live as an option just below Close All Tabs. This way we are consistent with the structure of the Overflow menu on a BrowserView.

**Comment by darinwf** [comment]
I added this to the iOS design sync for today. Time permitting we will cover it today, else can pick it up at the design open hours.

**Comment by Ria-yu** [comment]
Designer input:
It looks good (looks like you're re-using "find on page" UI). I'd change the copy to "Search Tabs" instead to match common practice, and please check the [figma mocks](https://www.figma.com/file/t1jW7cahkClVHAIlnHJuv8/Tab-Manager-(Spaces-%26-Tab-Groups)?node-id=3893%3A21430) for details

**Review by darinwf — APPROVED** [review]
LGTM

**Pull request merged**
