### PR TITLE
Address welcome screen experiment feedback

### PR DESCRIPTION
**Pull request by chung-lai**
Couple feedback from: #3799 

* Remove `the` from the first screen body before `ads`
* Change body text color

| Arm 1 | Arm 2 |
| --- | --- |
|  Screen Shot 2022-06-07 at 6 49 33 PM |  Screen Shot 2022-06-07 at 6 47 26 PM |

### How was this tested?
- [x] I tested this manually
- [ ] I added automated tests
- [ ] Existing automated tests are enough to cover my changes

### CODE REVIEW

**Review by jedireza — APPROVED** [review]

**Comment by hwiatneeva** [comment]
LGTM from design. Thanks Chung!

Adding SVG images here in case they can be part of this PR.
img-arm-1

bg-gradient
img-arm-2

**Comment by hwiatneeva** [comment]
Two images, @chung-lai 
img-arm-2
img-arm-1

**Comment by hwiatneeva** [comment]
@chung-lai  -- could you please try these l
Arm 1 -- for No Ads. No Tracking
img-arm-1
atest SVGs? 


Arm 2 -- for Privacy Made Easy
img-arm-2

The shield has been remade -- we need to confirm that's not broken. 

Preview -- hope we got all correct, but i'm not entirely certain at this point looking at the pixels for too long:
image

**Comment by hwiatneeva** [comment]
From design:  Final LGTM. Thanks much Chung!

**Comment by chung-lai** [comment]
> From design: Final LGTM. Thanks much Chung!

Thank you Hwi! Appreciate all the back and forth :)

**Comment by bikramneeva** [comment]
Experience looks good . Thanks

**Pull request merged**
