### PR TITLE
move to xcode13.3

### PR DESCRIPTION
**Pull request by EdwardJTL**
Move CircleCI to Xcode 13.3
For compatibility with xcode 13.3:
- Move swift-format to new [release](https://github.com/apple/swift-format/releases/tag/0.50600.0) 
- Move apollo to [0.51.0](https://github.com/apollographql/apollo-ios/issues/2146)

Verified that circle ci still builds and runs swift-format

### How was this tested?
- [ ] I tested this manually
- [ ] I added automated tests
- [x] Existing automated tests are enough to cover my changes

### CODE REVIEW

**Review by darinwf — COMMENTED** [review]
Looks like the swift-format step is still unhappy.

**Comment by EdwardJTL** [comment]
> Looks like the swift-format step is still unhappy.

we are good now! :P

**Review by darinwf — APPROVED** [review]
LGTM... some of those test failures might be due to this PR?

The TabManagerStoreTests one is definitely flaky and not due to this PR. I've been meaning to disable it.

**Comment by chung-lai** [comment]
@yozuysal was having issue uploading a build with XCode 13.3 so we may want to hold off merging this until we can upload a build with latest version of XCode.

This is the issue @yozuysal was seeing: https://developer.apple.com/forums/thread/701949

**Comment by EdwardJTL** [comment]
I'm investigating why these tests are failing too. lets wait haha

**Comment by chung-lai** [comment]
Looking at the apple forum, looks like Apple has [fixed the bug](https://developer.apple.com/forums/thread/701949?answerId=708133022#708133022) on their side about build upload. However, if this change will require everyone in the team to upgrade to XCode 13.3, may as well hold off till we push the release before merging this.

**Pull request merged**
