### PR TITLE
Enable ArchivedTabResign

### PR DESCRIPTION
**Pull request by evancrow**
### How was this tested?
- [x] Existing automated tests are enough to cover my changes

### CODE REVIEW

**Comment by evancrow** [comment]
Empty data text:

**Comment by darinwf** [comment]
One behavioral change I noticed:

When clicking on a tab in the archived tabs view, it no longer loads that tab. Instead, it just shows the card grid with that tab selected.

I think this is not very ideal for two reasons: 1) I think the user more likely wants to see that page if they click on it in the archived tabs view and 2) we don't have a thumbnail saved for archived tabs so all you see in the card grid is a tab with a blank thumbnail--which doesn't look so great.

**Review by darinwf — COMMENTED** [review]
Otherwise, this change LGTM.

**Comment by evancrow** [comment]
Fixed:

https://user-images.githubusercontent.com/37356984/193710135-14723357-b38f-4487-bbb7-da170c5e5bf4.mp4

**Review by darinwf — APPROVED** [review]

**Pull request merged**
