### PR TITLE
Experiment on default browser welcome screen

### PR DESCRIPTION
**Pull request by chung-lai**
Experiment on various welcome screen copy and asset.

### How was this tested?
- [x] I tested this manually
- [ ] I added automated tests
- [ ] Existing automated tests are enough to cover my changes

| First Screen | Second Screen |
| --- | --- |
| Screen Shot 2022-06-06 at 5 55 40 PM |  Screen Shot 2022-06-06 at 5 55 43 PM |
|  Screen Shot 2022-06-06 at 5 55 59 PM |  Screen Shot 2022-06-06 at 5 56 01 PM |
| Screen Shot 2022-06-06 at 5 58 36 PM | Screen Shot 2022-06-06 at 5 58 37 PM |
| Screen Shot 2022-06-06 at 5 58 12 PM | Screen Shot 2022-06-06 at 5 58 14 PM |

### CODE REVIEW

**Review by jedireza — APPROVED** [review]
I didn't test drive. Code looks good.

**Comment by chung-lai** [comment]
Please feel free to leave any feedback and will address them in a separate PR.

**Comment by darinwf** [comment]
copy nit: "You're just a step away from ad-free search, and browsing without **_the_** ads, trackers and pop-ups"

^^^ nuke "**_the_**"

**Comment by hwiatneeva** [comment]
> copy nit: "You're just a step away from ad-free search, and browsing without **_the_** ads, trackers and pop-ups"
> 
> ^^^ nuke "**_the_**"

@bikramneeva to confirm -- Thanks!

**Comment by hwiatneeva** [comment]
@chung-lai  feedback for now before updating with images

* The **text color** below the headlines, 'You're just a step away...' (screen 1) and 'With Neeva as your ...' (screen 2):  let's make them **SystemGray/03** (i.e. darker than Label/Light/Secondary), or something similar & available: 
image
image
image

**Comment by bikramneeva** [comment]
@Chung Lai ***@***.***> confirming -lets take out "the" as Darin
suggested.

 "You're just a step away from ad-free search, and browsing without ads,
trackers and pop-ups"

**Pull request merged**
