### PR TITLE
Correct "load in background" functionality

### PR DESCRIPTION
**Pull request by jonathangarelick**
This PR corrects the "load in background" functionality inherited from Firefox iOS.

Meta-note: Apologies if this is a bit messy, I'm new to Swift. Happy to make any adjustments as needed. Also, if you'd prefer this functionality be hidden (as mentioned in the issue), I can take care of that as well.

### How was this tested?
- [x] I tested this manually
- [ ] I added automated tests
- [ ] Existing automated tests are enough to cover my changes

### Manual test cases
See video below.

### Screenshots and screen recordings
https://user-images.githubusercontent.com/41495718/156946416-795ff72e-fd9a-4dcc-8e50-ea859eecc8b3.mov

## Issues addressed
* https://github.com/neevaco/neeva-ios/issues/2483

### CODE REVIEW

**Comment by jonathangarelick** [comment]
Here's an example with multiple tabs queued in the background. I'm not sure if the lazy loading is intentional or relevant, but you can see it at the end.

https://user-images.githubusercontent.com/41495718/156946782-e2727b01-d25d-4f97-9b91-864626c1cf21.mov

**Comment by jonathangarelick** [comment]
After doing some more research, my code is a bit wrong. The `loadQueuedTabs` function doesn't seem to do much -- the real action takes place in `dequeueQueuedTabs`. I'll have to spend some more time digging into this.

**Comment by jonathangarelick** [comment]
Alright, if someone could take a look at this, it's a bit cleaner now. A couple of notes:
- Dead code removed from AppDelegate.swift
- This code now differs from Firefox's in that the queued tab loading triggers in the `sceneDidBecomeActive` lifecycle hook rather than `applicationDidBecomeActive` [link to FF code for reference](https://github.com/mozilla-mobile/firefox-ios/blob/e155ab6555e03805ca1b363e9a89f7499ff559e5/Client/Application/AppDelegate.swift#L366)
- I don't know if it's still necessary to run the tab loading "on the background queue" due to the lifecycle hook change, but I left that functionality the same, along with the accompanying assertion.
- I don't quite understand the whole purpose of `receivedURLs`. There is a comment about receiving URLs from push notifications, but I can't imagine that this is part of the Neeva app right now (perhaps related to Pocket integration?)

Testing again --

https://user-images.githubusercontent.com/41495718/157125794-ab7409b5-0f77-4ed5-b76e-1e411127af0f.mov

**Review by darinwf — APPROVED** [review]
Makes sense! Thanks, LGTM

**Pull request merged**
