### PR TITLE
Feedback Email Field Text Cutoff Issue #3481

### PR DESCRIPTION
**Pull request by yasminyin96**
* Add floating label
* Modify padding

### How was this tested?
- [x] I tested this manually
- [ ] I added automated tests
- [ ] Existing automated tests are enough to cover my changes

### Screenshots and screen recordings
Screen Shot 2022-05-10 at 9 36 45 AM

Screen Shot 2022-05-10 at 9 36 59 AM

Screen Shot 2022-05-10 at 9 37 47 AM

### CODE REVIEW

**Comment by EdwardJTL** [comment]
Could you use the template for the PR description please :)

**Comment by yasminyin96** [comment]
Yes, could you please have a look at it? I'm not sure that the template I found is correct.

**Comment by EdwardJTL** [comment]
> Yes, could you please have a look at it? I'm not sure that the template I found is correct.

Yup that looks correct!

@chung-lai should we get Ria's input on this? Now the texts are different sizes. Maybe we should have this as a multiline text field too, or move the description outside of the text box?

**Comment by yasminyin96** [comment]
> Yup that looks correct!

Thank you!

**Comment by darinwf** [comment]
Yes, would be good to review this w/ @Ria-yu during open hours next week.

**Comment by darinwf** [comment]
> Yes, would be good to review this w/ @Ria-yu during open hours next week.

I added this topic to today's iOS design sync as we should have time for this one.

**Comment by yasminyin96** [comment]
* Add floating label to Description and Email text fields

### How was this tested?
- [x] I tested this manually
- [ ] I added automated tests
- [ ] Existing automated tests are enough to cover my changes

### Screenshots and screen recordings
<video src="https://user-images.githubusercontent.com/104786010/167523898-35a7366e-891d-467d-9595-1e6fb9e7f445.mov">

**Comment by chung-lai** [comment]
> * Add floating label to Description and Email text fields
> 
> ### How was this tested?
> * [x]  I tested this manually
> * [ ]  I added automated tests
> * [ ]  Existing automated tests are enough to cover my changes
> 
> ### Screenshots and screen recordings
>  Screen.Recording.2022-05-09.at.5.53.48.PM.mov

Feel free to modify the description and the description of the PR should reflect the latest changes.

**Review by chung-lai — COMMENTED** [review]
The change looks good to me. A couple things:

* the padding between the title and the content seem to be a bit big. You can inspect figma and see what's the padding
* you may want to try out on various screens to make sure it's working as expected

And we should tag Ria for review after the padding change. Thanks!

**Comment by chung-lai** [comment]
I think the padding is too small. Looks like there is about 10px between the two labels.

Screen Shot 2022-05-16 at 12 26 56 PM

**Pull request closed without merging**
