### PR TITLE
Update feedback toast message Fixes #3997

### LINKED ISSUE #3997: Update feedback toast message
Per discussion on `#design-mobile`, we decided to change the feedback toast message from "Feedback Submitted!" to "Sent. Thanks for your feedback!"

This is for parity between iOS and Android.

### PR DESCRIPTION
**Pull request by FloatingDorito**
change the feedback toast message from "Feedback Submitted!" to "Sent. Thanks for your feedback!"
Fixes #3997

### CODE REVIEW

**Comment by yozuysal** [comment]
Thanks so much for the PR!

Do you mind adding

Fixes Issue #3997 

to the end of your commit message so that we can close the issue when this lands?

**Comment by FloatingDorito** [comment]
> Thanks so much for the PR!
> 
> Do you mind adding
> 
> Fixes Issue #3997
> 
> to the end of your commit message so that we can close the issue when this lands?

Hi, of course! May I know how to add the said commit message?

**Review by FloatingDorito — COMMENTED** [review]
Update Feedback Toast Message Fix Issue #3997

**Comment by FloatingDorito** [comment]
> > > Thanks so much for the PR!
> > > Do you mind adding
> > > Fixes Issue #3997
> > > to the end of your commit message so that we can close the issue when this lands?
> > 
> > 
> > Hi, of course! May I know how to add the said commit message?
> 
> [Here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) is a guide on how to link PRs to issues. I believe you can actually just edit your PR description ("change the feedback toast message...") and add "Fixes #3997" at the bottom.

Hi, I'm done changing, is this correct?

**Review by yozuysal — APPROVED** [review]
Thank you!

**Comment by FloatingDorito** [comment]
@yozuysal May I ask how long this will take to close after approval?

**Pull request merged**
