### PR TITLE
Fix neeva memory page crash when navigate from history panel's clear data

### LINKED ISSUE #4141: Crash on opening neeva memory page from history
1. Open overflow menu
2. Open History
3. Go to "Clear Browsing Data" 
4. Go to "Manage Neeva Memory"

App crash

Note that this does not happen when navigate from settings page

### PR DESCRIPTION
**Pull request by chung-lai**
Fix #4141 

### How was this tested?
- [x] I tested this manually
- [ ] I added automated tests
- [ ] Existing automated tests are enough to cover my changes

### CODE REVIEW

**Review by darinwf — APPROVED** [review]
Can you also add a quick test for this?

**Comment by chung-lai** [comment]
> Can you also add a quick test for this?

The "Neeva Memory" option is behind Neeva feature flag and available only for signed in users. Not sure it'll be a quick test :)

**Comment by chung-lai** [comment]
> > Can you also add a quick test for this?
> 
> The "Neeva Memory" option is behind Neeva feature flag and available only for signed in users. Not sure it'll be a quick test :)

Nvm, think we can override the feature flag and simply open the link to make sure it's working though it may not load the page properly.

**Review by darinwf — COMMENTED** [review]
LGTM, thanks for the test!

**Pull request merged**
