### PR TITLE
CircleCI Changes

### PR DESCRIPTION
**Pull request by evancrow**
Fixes for CircleCI caused by a breakage from #2923 

FYI @j-f1

### CODE REVIEW

**Comment by j-f1** [comment]
If that works, you should be able to add `-v2` to the cache keys to retain the benefits of the cache while throwing out any old caches.

**Comment by evancrow** [comment]
Working now @j-f1!

**Review by chassu — APPROVED** [review]
Can you explain the v2 thing?

**Comment by evancrow** [comment]
The V2 just changes the ID of the cache. That way the simulated mac has to rebuild Carthage using the new XCFramework.

**Pull request merged**
