### PR TITLE
Add Creating jpeg Data Using CGImageDestination

### LINKED ISSUE #3001: PDF thumbnails are not saved
As part of investigating why thumbnails are sometimes blank (see https://github.com/neevaco/neeva-ios/issues/2838), I've noticed that PDF thumbnails are never saved.

### PR DESCRIPTION
**Pull request by EdwardJTL**
As listed on the issue, we cannot save thumbnails of pdfs because of unsupported pixel format in the UIImage. 
```
writeImageAtIndex:756: *** CMPhotoCompressionSessionAddImage: err = kCMPhotoError_UnsupportedPixelFormat [-16995]    (codec: 'jpeg')
```

We also identified that the cgImage object is still valid. As a workaround, we using CGImageDestination as a fallback method to create the jpeg data.

### How was this tested?
- [ ] I tested this manually
- [ ] I added automated tests
- [ ] Existing automated tests are enough to cover my changes

### Manual test cases
Open a link to pdf, open another tab. look at them in the tab switcher, open a tab again so the preserveTab function gets triggered. close the app and reopen. Verify in tab switcher.

### Screenshots and screen recordings

https://user-images.githubusercontent.com/44557675/157605902-dd91234a-3e5c-4ded-93ad-5c4a74dbb1b7.MP4

## Issues addressed
resolves #3001

### CODE REVIEW

**Comment by EdwardJTL** [comment]
there is still no title on the card tho. not sure why that is...

**Comment by darinwf** [comment]
> As listed on the issue, we cannot save thumbnails of pdfs because of unsupported pixel format in the UIImage.
> 
> ```
> writeImageAtIndex:756: *** CMPhotoCompressionSessionAddImage: err = kCMPhotoError_UnsupportedPixelFormat [-16995]    (codec: 'jpeg')
> ```

For future reference, how did you find this error message?

**Review by darinwf — APPROVED** [review]
Woohoo, nice!!!

**Comment by EdwardJTL** [comment]
> > As listed on the issue, we cannot save thumbnails of pdfs because of unsupported pixel format in the UIImage.
> > ```
> > writeImageAtIndex:756: *** CMPhotoCompressionSessionAddImage: err = kCMPhotoError_UnsupportedPixelFormat [-16995]    (codec: 'jpeg')
> > ```
> 
> For future reference, how did you find this error message?

it is in the debug console. its usually buried under a bunch of UILogs about context menu though.
you should still be able to see this message now. the routine calls UIImage.jpegData first

**Pull request merged**
