### PR TITLE
[DON'T MERGE] Remove Safari Extension

### PR DESCRIPTION
**Pull request by evancrow**
Due to issues with Apple App Store review, we have decided to remove the Safari Extension, Extension in favor of submitting it as its own product. This PR removes all code from the Neeva iOS App.

### CODE REVIEW

**Comment by jedireza** [comment]
IIUC the ideal approach is to first create the independent app and then try our best to migrate current extension users to it before removing it from our core app.

**Comment by darinwf** [comment]
Is it possible to hold off on this PR until we know for sure that we need to do this? Can we build the extension as a standalone app in addition to having it bundled?

**Comment by evancrow** [comment]
Yes agreed, have this set up as needed. I just moved the separate app into the iOS App directory.

**Comment by evancrow** [comment]
@darinwf Is this no longer needed?

**Comment by evancrow** [comment]
Closing the PR, will keep the branch around though... just in case

**Pull request closed without merging**
