### PR TITLE
Disable flaky test `testSignInWithStaleLoginCookie()`

### PR DESCRIPTION
**Pull request by chassu**
### Security

- [x] Security impact of change has been considered
- [x] Code follows company security practices and guidelines

### CODE REVIEW

**Comment by evancrow** [comment]
I think my recent PR #2737 might have fixed this test actually

**Review by darinwf — CHANGES_REQUESTED** [review]
We should use the `skipTest` method of disabling a test. That way the test is still compiled. Also, sounds like Evan thinks we may not need to disable this test?

**Comment by evancrow** [comment]
Maybe try leaving the test unskipped in this PR to see if it works...

**Comment by chassu** [comment]
I'm seeing this test getting flaky on main again... adding `skiptest()`

**Review by darinwf — APPROVED** [review]

**Pull request merged**
