### PR TITLE
run swift format after compile sources

### PR DESCRIPTION
**Pull request by chassu**
run swiftformat after compiling sources since we no longer let it fix the format for us

### How was this tested?
- [x] I tested this manually

### CODE REVIEW

**Comment by EdwardJTL** [comment]
have you tried adding `--ignore-unparsable-files` option to the `swift-format` command in `Scripts/swift-format.sh`

**Comment by EdwardJTL** [comment]
also re:description of the PR, i don't think we were letting swift-format format the files. we are just asking it to lint.

**Comment by chassu** [comment]
I haven't tried `--ignore-unparsable-files` before, is it better to do so than swapping the order?

**Comment by EdwardJTL** [comment]
> I haven't tried `--ignore-unparsable-files` before, is it better to do so than swapping the order?

yea i feel that running a linter after compiling is not very natural

**Comment by chassu** [comment]
I'm not sure if I'm modifying in the right place... PTAL 🙏

**Comment by EdwardJTL** [comment]
> 

that options needs to be passed to the actual swift format call

**Comment by chung-lai** [comment]
> > I haven't tried `--ignore-unparsable-files` before, is it better to do so than swapping the order?
> 
> yea i feel that running a linter after compiling is not very natural

From what @chassu experienced, he was missing a curly brace in one file and that broke swiftformat so we may have hit a bug with swiftformat on unmatching braces. However, the linter was running before compilation and we couldn't see the actual compilation error. And imo, we usually run linter separately before commit and most of the time just let linter fix all the errors for us :). May be we can explore that given now we have swift-format circleci now?

**Comment by EdwardJTL** [comment]
> 

when there's an unmatched braces, if the file could be parsed, the error log tells you where it is missing a brace (albeit not as nice as xcode highlighting).

and yes, i agree that we can take linter out of compile step. we can do a git hook or a separate circle ci job that will push to the branch?

**Pull request closed without merging**
