### PR TITLE
[ios] add backlink snippet

### PR DESCRIPTION
**Pull request by macy-n**
- add uuid v2 to cheatsheet logging
- show reddit snippet

### Demo

https://user-images.githubusercontent.com/61707598/166865466-8d38f329-311c-4a5c-8003-ea1fc431efeb.mp4

### CODE REVIEW

**Comment by macy-n** [comment]
@chung-lai not sure if you cut the release yet, but if you already did, don't worry about this one, can wait until next week.

**Review by EdwardJTL — APPROVED** [review]
ideally we can extract the subreddit name so we may format it safely. It doesn't look like that is returned separately in the API response :/ i dont feel safe about extracting it by scanning for " : ". maybe future work?

**Comment by chung-lai** [comment]
> @chung-lai not sure if you cut the release yet or added all cherry-pick for today, but if you already did, don't worry about this one, can wait until next week.

We can still cherry-pick. I see it's making an API related change and adding a feature. Unless it's critical, we may want to hold off for next week. Having said that, the uuid change is pretty safe. Let me know if you want to cherry pick only that particular change so we can have the data sooner.

**Comment by chung-lai** [comment]
[PR](https://github.com/neevaco/neeva-ios/pull/3513) for adding uuid for cheatsheet events on the release branch

**Pull request merged**
