### PR TITLE
Stick ArchivedTabsView to bottom

### PR DESCRIPTION
**Pull request by yasminyin96**
* Stick ArchivedTabsView to bottom

### How was this tested?
- [X] I tested this manually

### Screenshots and screen recordings

https://user-images.githubusercontent.com/104786010/171741154-e0f705b9-bde5-48f1-8b2a-0e020017885b.mov

iPad
Screen Shot 2022-06-02 at 2 28 43 PM

Disabled ArchivedTabsView
Screen Shot 2022-06-02 at 2 27 24 PM

## Issues addressed
* https://github.com/neevaco/neeva-ios/issues/3488

### CODE REVIEW

**Comment by darinwf** [comment]
Not quite sure I understand how this change solves the issue. One thing I noticed is that things don't look right in landscape mode:

Simulator Screen Shot - iPhone 13 - 2022-06-02 at 14 56 04

**Comment by yasminyin96** [comment]
> Not quite sure I understand how this change solves the issue. One thing I noticed is that things don't look right in landscape mode:
> 
> Simulator Screen Shot - iPhone 13 - 2022-06-02 at 14 56 04


I thought that if tab row is less than 2, the archivedview will stick to the bottom. But it seems not work for landscape. I will take a look.
I found that this issue also exists on main with no tab.
IMG_3920

**Comment by chung-lai** [comment]
> > Not quite sure I understand how this change solves the issue. One thing I noticed is that things don't look right in landscape mode:
> > Simulator Screen Shot - iPhone 13 - 2022-06-02 at 14 56 04
> 
> I thought that if tab row is less than 2, the archivedview will stick to the bottom. But it seems not work for landscape. I will take a look. I found that this issue also exists on main with no tab. IMG_3920

fyi @chassu about the issue on main with no tab in archived tabs

**Comment by yasminyin96** [comment]
> Test drove; makes sense. We can solve the landscape issue in a separate PR since it isn't introduced by this PR.

Got it. I'll create an issue for the landscape issue. Thank you.

**Pull request merged**
